# SPDX-License-Identifier: MIT OR Apache-2.0

name: Rust CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
permissions: {}

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install cargo-hack
        uses: taiki-e/install-action@60ae4ce63c7aeb6e96d7f572c1ec7fafbb17ca80 # v2.79.10
        with:
          tool: cargo-hack

      - name: Install Nightly Rust Toolchain
        run: |
          rustup toolchain install nightly --profile minimal --component rustfmt,clippy --no-self-update
          rustup default nightly

      - name: Install Boost
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev

      - name: Spell check
        uses: crate-ci/typos@7b04f660f4ee4f048d18fd341887cf28dfbedfe2 # v1.46.3
        with:
          config: ./_typos.toml

      - name: Run cargo fmt
        run: cargo +nightly fmt --all --check

      - name: Run cargo doc
        run: |
          RUSTDOCFLAGS="--cfg docsrs -D warnings" \
          cargo +nightly doc --workspace --no-deps --lib --all-features --document-private-items

      - name: Run cargo clippy
        run: ./contrib/feature_matrix.sh clippy '-- -D warnings'
        shell: bash # Ensure the script runs using bash on all platforms

  cross-testing:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install 1.85.0 Rust Toolchain
        run: |
          rustup toolchain install 1.85.0 --profile minimal --component rustfmt,clippy --no-self-update
          rustup default 1.85.0

      - name: Install cargo-hack
        uses: taiki-e/install-action@60ae4ce63c7aeb6e96d7f572c1ec7fafbb17ca80 # v2.79.10
        with:
          tool: cargo-hack

      - name: Install Boost (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev

      - name: Install Boost (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install boost

      - name: Install Boost library
        if: runner.os == 'Windows'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg install boost-multi-index:x64-windows-static boost-headers:x64-windows-static
          echo "VCPKG_ROOT=$env:GITHUB_WORKSPACE\vcpkg" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "$env:GITHUB_WORKSPACE\vcpkg\installed\x64-windows-static\lib" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Set environment variables for static linking
        if: runner.os == 'windows'
        run: |
          echo "BOOST_ROOT=$env:GITHUB_WORKSPACE\vcpkg\installed\x64-windows-static" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "BOOST_INCLUDEDIR=$env:GITHUB_WORKSPACE\vcpkg\installed\x64-windows-static\include" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "BOOST_LIBRARYDIR=$env:GITHUB_WORKSPACE\vcpkg\installed\x64-windows-static\lib" | Out-File -FilePath $env:GITHUB_ENV -Append

      # Bi-weekly numbers to refresh caches every two weeks, ensuring recent project changes are cached
      - name: Set bi-weekly cache key
        # Use '10#' to always treat week number as base-10 (avoids octal when number has a leading zero)
        run: |
          YEAR=$(date +%Y)
          WEEK=$(date +%U)
          BIWEEK=$(( (10#$WEEK + 1) / 2 ))
          echo "CACHE_VERSION=${YEAR}(${BIWEEK})" >> $GITHUB_ENV
        shell: bash

      # Restore cached dependencies and build artifacts
      - name: Restore Rust cache
        id: cache
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/release/
          # Cache key depends on the bi-week we are on (cache version)
          key: ${{ runner.os }}-cargo-${{ env.CACHE_VERSION }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ env.CACHE_VERSION }}-
            ${{ runner.os }}-cargo-

      # Build only the binaries
      - name: Build binaries
        run: cargo build --release --bins --verbose

      # Run the feature testing script
      - name: Run feature tests
        run: ./contrib/feature_matrix.sh test --verbose
        shell: bash # Ensure the script runs using bash on all platforms

      # Save cache only if the previous steps succeeded and there was not an exact cache key match
      # This happens everytime we modify any `cargo.lock` or `cargo.toml`, or each two weeks (caching recent changes)
      - name: Save Rust cache
        if: success() && steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/release/
          key: ${{ steps.cache.outputs.cache-primary-key }}

  no-std:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - crate: floresta-common
            feature_args: ""

    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install 1.85.0 Rust Toolchain and no-std Target
        run: |
          rustup toolchain install 1.85.0 --profile minimal --target thumbv7em-none-eabi --no-self-update
          rustup default 1.85.0

      - name: Install ARM GCC (for secp256k1-sys)
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi

      - name: Build ${{ matrix.crate }} for no_std target
        shell: bash
        run: |
          cargo build -p "${{ matrix.crate }}" \
            --target thumbv7em-none-eabi \
            --no-default-features \
            ${{ matrix.feature_args }} \
            --locked

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Cache Docker layers
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('contrib/docker/Dockerfile') }}

      - name: Build Docker image
        run: |
          docker buildx build \
          --cache-to=type=local,dest=/tmp/.buildx-cache \
          --cache-from=type=local,src=/tmp/.buildx-cache \
          -f contrib/docker/Dockerfile \
          -t dlsz/floresta:latest .
